### ISSUE TITLE
Cannot Access EZ_ADJUST and IN START 

### ISSUE THREAD

**Issue by thirdgarcia** [ypid/lgcommander#2]
Hi I tried to execute command 255 and 251 in my LG LA6200 but gives me no response.

How can I access my service menu? thanks

**Comment by ypid** [comment]
Can you execute other commands? Unfortunatly, I have no idea how you can access the service menu as I have never done this …

**Comment by thirdgarcia** [comment]
I was able to execute volume up and volume down...

I need to execute 255 and 251 but i can't... thanks

**Comment by ypid** [comment]
Thanks to  @ubaransel for answering this. See issue https://github.com/ubaransel/lgcommander/issues/10
@thirdgarcia sorry that I could not help you. If you find a way, let us now :smile:
