### ISSUE TITLE
Syntax error - Raspberry Pi

### ISSUE THREAD

**Issue by pbriesch** [ypid/lgcommander#3]
Hello,

on the RaspberryPi I get following Syntax Error:

```
pi@rpi2 ~/lgcommander $ python3 lgcommander.py
  File "lgcommander.py", line 29
    top.title(u"Lg Commander")
                            ^
SyntaxError: invalid syntax
pi@rpi2 ~/lgcommander $
```

Debian (raspbian) wheezy, Python 3.2.3, and the Linux version is:

```
Linux version 3.18.14-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #793 SMP PREEMPT Sat May 30 14:04:35 BST 2015
```

On my x86-PC lgcommander runs without error.
Ubuntu vivid, Python 3.4.3, and the Linux version is:

```
Linux version 3.19.0-18-generic (buildd@lamiak) (gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) ) #18-Ubuntu SMP Tue May 19 18:30:59 UTC 2015 (Ubuntu 3.19.0-18.18-generic 3.19.6)
```

Regards, Paul

**Comment by ypid** [comment]
Try to replace all `u"` with `"`. `s/u"/"/g`. Because it is Python3 all strings are in Unicode by default.

**Comment by pbriesch** [comment]
Thanks for your reply.
I have deleted all instances of u before a string and now it works fine on the RaspberryPi and x86.
