### ISSUE TITLE
not supportett protocol on lg 2016 (webos 3.0)

### ISSUE THREAD

**Issue by mycop5** [ypid/lgcommander#6]
python lgcommander.py
# DEBUG: Returned: HTTP/1.1 200 OK
Location: http://192.168.1.36:1718/
Cache-Control: max-age=1800
Server: Linux/i686 UPnP/1,0 DLNADOC/1.50 LGE WebOS TV/Version 0.9
EXT:
USN: uuid:b4528211-0000-0000-c000-27e585bd6e41::urn:schemas-upnp-org:device:Medi
aRenderer:1
ST: urn:schemas-upnp-org:device:MediaRenderer:1
Date: Wed, 24 May 2017 19:11:23 GMT
DLNADeviceName.lge.com: %5bLG%5d%20webOS%20TV%20UH950V

# DEBUG: Found device: 192.168.1.36
# INFO: Using device: 192.168.1.36 over transport protocol: 8080/tcp
# DEBUG: Detecting accepted protocol.
# DEBUG: Trying to connect to port 3000/tcp
Traceback (most recent call last):
  File "lgcommander.py", line 348, in <module>
    main()
  File "lgcommander.py", line 305, in main
    protocol=user_parms.protocol)
  File "lgcommander.py", line 70, in __init__
    self.auto_detect_accepted_protocol()
  File "lgcommander.py", line 119, in auto_detect_accepted_protocol
    raise Exception("Protocol not supported. See https://github.com/ypid/lgcomma
nder/issues/1")
Exception: Protocol not supported. See https://github.com/ypid/lgcommander/issues/1

**Comment by ypid** [comment]
> Exception: Protocol not supported. See #1

Seen that? Please refer to https://github.com/ypid/lgcommander/issues/1. I am closing this issue. Welcome to GitHub by the way :)

Related to: https://github.com/ubaransel/lgcommander/issues/13

**Comment by mycop5** [comment]
As i understand this script is just not supported new tv? Right?

**Comment by ypid** [comment]
Yes, this script does not support newer TVs.

**Comment by cleemullins** [comment]
Ah well. I was excited to play with the service menu on my OLED TV via this, but I guess it's off to buy an IR remote I can program. 

(The LG Global Dimming is driving me nuts. I've got a beautiful 55" OLED screen that goes "dim" every 60 seconds if the screen doesn't change enough. Makes writing code very difficult.)
